config:
  TEXT_PROMPT: "characters in cartoon"
  SAM2_CHECKPOINT: "/home/serverai/ltdoanh/LayoutGeneration/objectfree/Grounded-SAM-2/checkpoints/sam2.1_hiera_tiny.pt"
  SAM2_MODEL_CONFIG: "/configs/sam2.1/sam2.1_hiera_t.yaml"
  GROUNDING_DINO_MODEL: "IDEA-Research/grounding-dino-tiny"
  BOX_THRESHOLD: 0.2
  TEXT_THRESHOLD: 0.2
  NMS_THRESHOLD: 0.3
  SIMILARITY_THRESHOLD: 0.5
  USE_WBF: False  # Disable WBF to keep more detections
